language: go

os:
- linux

env:
- GO111MODULE=on


install:
- pushd pkg && make getdeps && popd

script:
- pushd pkg && make verifiers && popd
- pushd pkg && make coverage && popd
- pushd cmds && make && popd
- pushd tools && make && popd

go:
- '1.13'
