entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"
providers:
  file:
    directory: "%s/proxy"
    watch: true
certificatesResolvers:
  resolver:
    acme:
      # email: your-email@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
