apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 173.30.1.240-173.30.1.250
    - name: public
      protocol: layer2
      addresses:
      - 173.30.3.240.165-173.30.3.240.169
      auto-assign: false
---
apiVersion: v1
kind: Service
metadata:
  name: apiserverlb
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: public
spec:
  ports:
    - port: 543
      targetPort: 6443
  type: LoadBalancer
  loadBalancerIP: 173.30.3.168
