@url = tfgrid.workloads.reservation.workload.1
workload_id = (S)
user = (S)
type = "zdb,container,volume,network,kubernetes" (E)
content = (dict)
created = (T)
duration = (I)
signature = (S)
to_delete = (B)
