
@url = tfgrid.workloads.reservation.1
#json of the reservation.data object, will not change over time
json = "" (S)
data_reservation = (O) !tfgrid.workloads.reservation.data.1
#id of threebot which pays for it
customer_tid = (I)
#signature with private key of customer of the json, this guarantees that the data did not change
customer_signature = (S)
#state, allows anyone to see what can happen next e.g. sign means waiting for everyone to sign
#delete means its deployed now we need to wait till enough people sign to delete
next_action = "create,sign,pay,deploy,delete,invalid,deleted" (E)
signatures_provision = (LO) !tfgrid.workloads.reservation.signing.signature.1
signatures_farmer = (LO) !tfgrid.workloads.reservation.signing.signature.1
signatures_delete = (LO) !tfgrid.workloads.reservation.signing.signature.1
epoch = (T)
results = (LO) !tfgrid.workloads.reservation.result.1

@url = tfgrid.workloads.reservation.data.1
#this one does not change over time
description = "" (S)
#list of acceptable currencies for this reservation
currencies = (LS)
#need toget to consensus
signing_request_provision = (O) !tfgrid.workloads.reservation.signing.request.1
signing_request_delete = (O) !tfgrid.workloads.reservation.signing.request.1
containers = (LO) !tfgrid.workloads.reservation.container.1
volumes = (LO) !tfgrid.workloads.reservation.volume.1
zdbs = (LO) !tfgrid.workloads.reservation.zdb.1
networks = (LO) !tfgrid.workloads.reservation.network.1
kubernetes = (LO) !tfgrid.workloads.reservation.k8s.1
#till whe is request for provisioning valid, if not signed in required time then obsolete
expiration_provisioning = (T)
#till whe is reservation valid
expiration_reservation = (T)

@url = tfgrid.workloads.reservation.signing.request.1
#part of the reservation.data, because should never be possible to delete this
#threebotids of people who can sign
signers = (LI)
#min nr of people who need to sign
quorum_min = (I)

@url = tfgrid.workloads.reservation.signing.signature.1
#threebotid
tid = (I)
#signature in string form of the json as stored in the root of this obj
signature = (S)
#time of signature
epoch = (T)
