name: flist build
on: [push]
jobs:

  build:
    name: Flist build
    runs-on: ubuntu-latest
    steps:

    - name: Set up go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        cd cmds
        make
      env:
        GO111MODULE: on

    - name: Collecting files
      run: |
        mkdir -p /tmp/archive/{bin,etc/zinit}
        cp bin/* /tmp/archive/bin/
        cp -r zinit/* /tmp/archive/etc/zinit

    - name: Build FList 
      if: success()
      uses: threefoldtech/action-publish@v1-release
      with:
        user: tf-autobuilder
        root: /tmp/archive
        token: ${{ secrets.HUB_JWT }}
        name: zos-${{ github.sha }}.tar.gz
