on: issues
name: Add new issues to projects
jobs:
  build:
    name: alex-page/add-new-issue-project
    runs-on: ubuntu-latest
    steps:
    - name: alex-page/add-new-issue-project
      uses: alex-page/add-new-issue-project@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '"zero-os_2.0.0 (active)" "To do"'

