#is the location, 1 specific farm
@url = tfgrid.directory.farm.1
threebot_id** = (I)
iyo_organization = (S) # for backward compatibility
name** = (S)
wallet_addresses = (LO) !tfgrid.directory.wallet_address.1
location = (O) !tfgrid.directory.location.1
email = (email)
resource_prices = (LO) !tfgrid.directory.node.resource.price.1
# original /48 allocation of the farm
prefix_zero = (iprange)


@url = tfgrid.directory.wallet_address.1
asset = (S)
address = (S)

@url = tfgrid.directory.node.resource.price.1
currency = "EUR,USD,TFT,AED,GBP" (E)
cru = (F)
mru = (F)
hru = (F)
sru = (F)
nru = (F)
